"""
translator.py
─────────────
Pure-logic module: tokenizes a SQL string and produces a SAS PROC SQL
pass-through block.  No Flask, no argparse, no file I/O.

Public API
──────────
    translate(sql: str, conn: str) -> dict
        {
            "sas":      str,
            "warnings": list[str],
            "counts":   {"total": int, "wrapped": int, "skipped": int},
        }

    Raises ValueError if no executable statements remain after filtering.
"""

import re


# ── tokenizer ──────────────────────────────────────────────────────────────────

def tokenize(sql: str) -> list[tuple[str, str]]:
    """
    Produce an ordered list of (kind, text) tokens:

        'line_comment'   -- standalone  -- comment between statements
        'block_comment'  -- standalone  /* comment */ between statements
        'statement'      -- one SQL statement (inline comments absorbed)

    Inline comments (inside an already-started statement) are absorbed into
    the statement text.  '--' inline comments are converted to /* */ since
    SAS does not support -- inside execute() bodies.
    """
    tokens: list[tuple[str, str]] = []
    current: list[str] = []
    in_single = False
    in_double = False
    i = 0
    n = len(sql)

    def in_statement() -> bool:
        return bool("".join(current).strip())

    def flush_stmt() -> None:
        text = "".join(current).strip()
        if text:
            tokens.append(("statement", text))
        current.clear()

    while i < n:
        ch = sql[i]

        if not in_single and not in_double:

            # -- line comment
            if ch == "-" and i + 1 < n and sql[i + 1] == "-":
                end = sql.find("\n", i)
                end = end if end != -1 else n
                comment_text = sql[i:end]
                if in_statement():
                    body = comment_text.lstrip("-").strip()
                    current.append(f" /* {body} */")
                else:
                    tokens.append(("line_comment", comment_text))
                i = end
                continue

            # /* block comment */
            if ch == "/" and i + 1 < n and sql[i + 1] == "*":
                end = sql.find("*/", i + 2)
                end = end + 2 if end != -1 else n
                comment_text = sql[i:end]
                if in_statement():
                    current.append(comment_text)
                else:
                    flush_stmt()
                    tokens.append(("block_comment", comment_text))
                i = end
                continue

            if ch == ";":
                flush_stmt()
                i += 1
                continue

        if ch == "'" and not in_double:
            if in_single and i + 1 < n and sql[i + 1] == "'":
                current.append("''")
                i += 2
                continue
            in_single = not in_single
        elif ch == '"' and not in_single:
            if in_double and i + 1 < n and sql[i + 1] == '"':
                current.append('""')
                i += 2
                continue
            in_double = not in_double

        current.append(ch)
        i += 1

    flush_stmt()
    return tokens


# ── comment conversion ─────────────────────────────────────────────────────────

def convert_comment_to_sas(kind: str, text: str) -> str:
    """Convert a standalone SQL comment token to a SAS /* … */ comment."""
    if kind == "block_comment":
        return text
    body = text.lstrip("-").strip()
    return f"/* {body} */" if body else "/* */"


# ── statement formatting ───────────────────────────────────────────────────────

def normalize_whitespace(stmt: str) -> str:
    stmt = re.sub(r"\n{3,}", "\n\n", stmt)
    lines = [line.rstrip() for line in stmt.splitlines()]
    return "\n".join(lines).strip()


def indent(text: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def wrap_as_execute(stmt: str, conn: str) -> str:
    body = indent(normalize_whitespace(stmt))
    return f"    execute (\n{body}\n    ) by {conn};"


# ── SAS block assembly ─────────────────────────────────────────────────────────

def build_sas_block(
    tokens: list[tuple[str, str]],
    conn: str,
    wrapped_count: int,
) -> str:
    header = (
        f"/* Generated by sql-to-sas-web\n"
        f"   Conn               : {conn}\n"
        f"   Statements wrapped : {wrapped_count}\n"
        f"*/"
    )

    body_parts: list[str] = []
    pending_comments: list[str] = []

    for kind, text in tokens:
        if kind in ("line_comment", "block_comment"):
            pending_comments.append("    " + convert_comment_to_sas(kind, text))
        else:
            if pending_comments:
                body_parts.append("\n".join(pending_comments))
                pending_comments = []
            body_parts.append(wrap_as_execute(text, conn))

    if pending_comments:
        body_parts.append("\n".join(pending_comments))

    body = "\n\n".join(body_parts)
    return (
        f"{header}\n\n"
        f"proc sql;\n"
        f"    connect to {conn};\n\n"
        f"{body}\n\n"
        f"    disconnect from {conn};\n"
        f"quit;"
    )


# ── public API ─────────────────────────────────────────────────────────────────

def translate(sql: str, conn: str) -> dict:
    """
    Translate a SQL string into a SAS PROC SQL pass-through block.

    Parameters
    ----------
    sql  : raw SQL source text
    conn : SAS connection/libname alias

    Returns
    -------
    {
        "sas":      str,
        "warnings": list[str],
        "counts":   {"total": int, "wrapped": int, "skipped": int},
    }

    Raises
    ------
    ValueError  if no executable statements remain after filtering SELECTs.
    """
    tokens = tokenize(sql)

    filtered_tokens: list[tuple[str, str]] = []
    warnings: list[str] = []
    total = 0
    skipped = 0
    stmt_index = 0

    for kind, text in tokens:
        if kind != "statement":
            filtered_tokens.append((kind, text))
            continue

        total += 1
        stmt_index += 1
        first_word = text.split()[0].upper() if text.split() else ""

        if first_word == "SELECT":
            skipped += 1
            preview = " ".join(text.split()[:12])
            if len(text.split()) > 12:
                preview += " …"
            warnings.append(
                f"Statement #{stmt_index} is a SELECT and will be skipped "
                f"(not executable via pass-through): {preview}"
            )
        else:
            filtered_tokens.append((kind, text))

    wrapped = total - skipped

    if wrapped == 0:
        raise ValueError(
            "No executable statements found after filtering SELECT statements."
        )

    sas = build_sas_block(filtered_tokens, conn=conn, wrapped_count=wrapped)

    return {
        "sas": sas,
        "warnings": warnings,
        "counts": {"total": total, "wrapped": wrapped, "skipped": skipped},
    }
